-- MySQL Script generated by MySQL Workbench
-- Mon Dec 15 16:13:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema products_manage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema products_manage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `products_manage` DEFAULT CHARACTER SET utf8 ;
USE `products_manage` ;

-- -----------------------------------------------------
-- Table `products_manage`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_manage`.`users` (
                                                         `id` INT NOT NULL AUTO_INCREMENT,
                                                         `email` VARCHAR(60) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `username` VARCHAR(45) NULL,
    `firstname` VARCHAR(45) NULL,
    `lastname` VARCHAR(45) NULL,
    `created_at` DATE NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products_manage`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_manage`.`category` (
                                                            `id` INT NOT NULL AUTO_INCREMENT,
                                                            `name` VARCHAR(45) NOT NULL,
    `description` LONGTEXT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products_manage`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_manage`.`products` (
                                                            `id` INT NOT NULL AUTO_INCREMENT,
                                                            `name` VARCHAR(40) NOT NULL,
    `brand` VARCHAR(45) NULL,
    `reference` VARCHAR(150) NULL,
    `quantity` INT NULL DEFAULT 0,
    `price` FLOAT NULL DEFAULT 0.00,
    `availability` TINYINT NULL DEFAULT 0,
    `category_id` INT NOT NULL,
    PRIMARY KEY (`id`, `category_id`),
    INDEX `fk_products_category_idx` (`category_id` ASC),
    CONSTRAINT `fk_products_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `products_manage`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products_manage`.`products_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products_manage`.`products_has_users` (
                                                                      `products_id` INT NOT NULL,
                                                                      `users_id` INT NOT NULL,
                                                                      PRIMARY KEY (`products_id`, `users_id`),
    INDEX `fk_products_has_users_users1_idx` (`users_id` ASC),
    INDEX `fk_products_has_users_products1_idx` (`products_id` ASC),
    CONSTRAINT `fk_products_has_users_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `products_manage`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_products_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `products_manage`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




    